[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer_runs = 44444444
ffi = false

[profile.default.fuzz]
runs = 256

[profile.ci.fuzz]
runs = 10000
